spring:
  profiles:
<<<<<<< HEAD
    active: dev
=======
<<<<<<< HEAD
    active: dev
=======
<<<<<<< HEAD
    active: dev
=======
<<<<<<< HEAD
    active: dev
=======
    active: prod
>>>>>>> 01cba11 (submit)
>>>>>>> e243474 (submit)
>>>>>>> 890ad90 (submit)
>>>>>>> b98947e (提交)
