

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://101.35.89.157:3306/pufdemo?characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: seugoodwayhouse88
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

mybatis-plus:
  configuration:
    # 配置MyBatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

initial:
  eccType: secp256r1


server:
  port: 9000

netty:
  port: 8500

jwt:
# JWT存储的请求头
  tokenHeader: Authorization
# JWT 加解密使用的密钥
  secret: managementkey
# JWT的超期限时间（60*60*24）
  expiration: 604800
# JWT 负载中拿到开头
  tokenHead: Bearer


