server:
  port: 9000

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://101.35.89.157:3306/pufdemo?characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: seugoodwayhouse88
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


initial:
  eccType: secp256r1