spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.35.89.157:3306/pufdemo?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

mybatis:
  mapper-locations: classpath:/mapper/*.xml

initial:
  eccType: secp256r1