server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.35.89.157:3306/pufdemo?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 12345678
  jpa:
    hibernate:
<<<<<<< HEAD
      ddl-auto: create
=======
<<<<<<< HEAD
      ddl-auto: create
=======
<<<<<<< HEAD
      ddl-auto: create
=======
<<<<<<< HEAD
      ddl-auto: create
=======
      ddl-auto: update
>>>>>>> 01cba11 (submit)
>>>>>>> e243474 (submit)
>>>>>>> 890ad90 (submit)
>>>>>>> b98947e (提交)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

mybatis-plus:
  configuration:
    # 配置MyBatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer

initial:
  eccType: secp256r1
